version: "2"
  
services:  
  fastapi:
    build: back/
    ports:
      - "80:8000"
    depends_on:
      - postgres
    env_file:
      - back/.env

  postgres:
    image: postgres
    POSTGRES_PASSWORD: password  
    POSTGRES_DB: mydb  
    volumes:
      - pgvolume  
    ports:
      - "5432:5432"
    env_file:
      - back/.env