version: "2"
  
services:  
  fastapi:
    build: back/
    ports:
      - "80:8000"
    depends_on:
      - postgres
    env_file:
      - back/.env

  postgres:
    image: postgres
    env_file:
      -back/.env
    volumes:
      - pgvolume  
    ports:
      - "5432:5432"